allow build on arm64

diff --git a/NodeFirefox/Dockerfile b/NodeFirefox/Dockerfile
--- a/NodeFirefox/Dockerfile
+++ b/NodeFirefox/Dockerfile
@@ -4,23 +4,20 @@ ARG AUTHORS
 FROM ${NAMESPACE}/node-base:${VERSION}
 LABEL authors=${AUTHORS}
 
+ARG TARGETARCH
+ARG TARGETVARIANT
+
 USER root
 
 #=========
 # Firefox
 #=========
-ARG FIREFOX_VERSION=latest
-RUN FIREFOX_DOWNLOAD_URL=$(if [ $FIREFOX_VERSION = "latest" ] || [ $FIREFOX_VERSION = "beta-latest" ] || [ $FIREFOX_VERSION = "nightly-latest" ] || [ $FIREFOX_VERSION = "devedition-latest" ] || [ $FIREFOX_VERSION = "esr-latest" ]; then echo "https://download.mozilla.org/?product=firefox-$FIREFOX_VERSION-ssl&os=linux64&lang=en-US"; else echo "https://download-installer.cdn.mozilla.net/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2"; fi) \
-  && apt-get update -qqy \
-  && apt-get -qqy --no-install-recommends install libavcodec-extra \
-     libgtk-3-dev libdbus-glib-1-dev \
-  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
-  && wget --no-verbose -O /tmp/firefox.tar.bz2 $FIREFOX_DOWNLOAD_URL \
-  && rm -rf /opt/firefox \
-  && tar -C /opt -xjf /tmp/firefox.tar.bz2 \
-  && rm /tmp/firefox.tar.bz2 \
-  && mv /opt/firefox /opt/firefox-$FIREFOX_VERSION \
-  && ln -fs /opt/firefox-$FIREFOX_VERSION/firefox /usr/bin/firefox
+RUN apt-get -qqy update \
+  && apt-get -qqy install libavcodec-extra software-properties-common \
+  && add-apt-repository ppa:mozillateam/ppa \
+  && apt-get -qqy update \
+  && apt-get -qqy install -t 'o=LP-PPA-mozillateam' firefox \
+  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
 
 #============
 # GeckoDriver
@@ -28,7 +25,23 @@ RUN FIREFOX_DOWNLOAD_URL=$(if [ $FIREFOX_VERSION = "latest" ] || [ $FIREFOX_VERS
 ARG GECKODRIVER_VERSION=latest
 RUN GK_VERSION=$(if [ ${GECKODRIVER_VERSION:-latest} = "latest" ]; then echo "0.33.0"; else echo $GECKODRIVER_VERSION; fi) \
   && echo "Using GeckoDriver version: "$GK_VERSION \
-  && wget --no-verbose -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v$GK_VERSION/geckodriver-v$GK_VERSION-linux64.tar.gz \
+  && if [ $TARGETARCH = "arm" ] && [ $TARGETVARIANT = "v7" ]; then \
+     ARCH=armhf ; \
+  else \
+     ARCH=$TARGETARCH ; \
+  fi \
+  && if [ -z "$ARCH" ]; then \
+     echo "*** BUILD ERROR: \$TARGETARCH must be arm64, amd64, or arm with \$TARGETVARIANT set to v7... exiting..." ; \
+     exit 1 ; \
+  fi \
+  && if [ "$ARCH" = "arm64" ]; then \
+     GK_DOWNLOAD_URL="https://github.com/mozilla/geckodriver/releases/download/v$GK_VERSION/geckodriver-v$GK_VERSION-linux-aarch64.tar.gz" ; \
+  elif [ "$ARCH" = "armhf" ]; then \
+     GK_DOWNLOAD_URL="https://github.com/jamesmortensen/geckodriver-arm-binaries/releases/download/v$GK_VERSION/geckodriver-v$GK_VERSION-linux-armv7l.tar.gz" ; \
+  else \
+     GK_DOWNLOAD_URL="https://github.com/mozilla/geckodriver/releases/download/v$GK_VERSION/geckodriver-v$GK_VERSION-linux64.tar.gz" ; \
+  fi \
+  && wget --no-verbose -O /tmp/geckodriver.tar.gz $GK_DOWNLOAD_URL \
   && rm -rf /opt/geckodriver \
   && tar -C /opt -zxf /tmp/geckodriver.tar.gz \
   && rm /tmp/geckodriver.tar.gz \
